
# Source: https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/common/nginx-config.yaml

# kubectl apply -f nginx/nginx-config.yaml

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
